name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  validate:
    name: Validate Dependencies and Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.0

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check dependency mismatches
        run: bun run dep:check

      - name: Validate dependency rules
        run: bun run dep:validate

      - name: Lint code
        run: bun run lint

      - name: Run tests
        run: bun run test

      - name: Build all projects
        run: bun run build

      - name: Check for uncommitted changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Uncommitted changes found after build:"
            git status --porcelain
            exit 1
          fi

  affected:
    name: Run Affected Commands
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.0

      - uses: nrwl/nx-set-shas@v4

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run affected lint
        run: bunx nx affected -t lint

      - name: Run affected tests
        run: bunx nx affected -t test

      - name: Run affected builds
        run: bunx nx affected -t build
